# -*- coding: utf-8 -*-
"""AI-Based Sentiment AnalyzerPhase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBywXbr4yxTCTQzUpb12rYxFWgRh1uQ3
"""

!pip install transformers torch matplotlib

from transformers import pipeline
import matplotlib.pyplot as plt

# Load sentiment analysis model
sentiment_pipeline = pipeline("sentiment-analysis")

def analyze_sentiment(text):
    result = sentiment_pipeline(text)[0]
    label = result['label']
    score = result['score']

    print("Text:", text)
    print("Sentiment:", label)
    print("Confidence Score:", round(score, 3))

    # Visualization
    plt.figure()
    plt.bar(label, score)
    plt.ylim(0, 1)
    plt.xlabel("Sentiment")
    plt.ylabel("Confidence Score")
    plt.title("Sentiment Analysis Result")
    plt.show()

# Example
text_input = input("Enter text to analyze sentiment: ")
analyze_sentiment(text_input)

